// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `PortDisconnected`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`

/// Serial port information
class PortInfo {
  final String name;
  final String portType;
  final String? manufacturer;
  final String? product;

  const PortInfo({
    required this.name,
    required this.portType,
    this.manufacturer,
    this.product,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      portType.hashCode ^
      manufacturer.hashCode ^
      product.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PortInfo &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          portType == other.portType &&
          manufacturer == other.manufacturer &&
          product == other.product;
}

/// Serial port configuration
class SerialConfig {
  final String portName;
  final int baudRate;
  final int dataBits;
  final String stopBits;
  final String parity;
  final bool dtr;
  final bool rts;

  const SerialConfig({
    required this.portName,
    required this.baudRate,
    required this.dataBits,
    required this.stopBits,
    required this.parity,
    required this.dtr,
    required this.rts,
  });

  @override
  int get hashCode =>
      portName.hashCode ^
      baudRate.hashCode ^
      dataBits.hashCode ^
      stopBits.hashCode ^
      parity.hashCode ^
      dtr.hashCode ^
      rts.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SerialConfig &&
          runtimeType == other.runtimeType &&
          portName == other.portName &&
          baudRate == other.baudRate &&
          dataBits == other.dataBits &&
          stopBits == other.stopBits &&
          parity == other.parity &&
          dtr == other.dtr &&
          rts == other.rts;
}

/// Data received from serial port
class SerialData {
  final String portName;
  final Uint8List data;
  final BigInt timestamp;

  const SerialData({
    required this.portName,
    required this.data,
    required this.timestamp,
  });

  @override
  int get hashCode => portName.hashCode ^ data.hashCode ^ timestamp.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SerialData &&
          runtimeType == other.runtimeType &&
          portName == other.portName &&
          data == other.data &&
          timestamp == other.timestamp;
}
