// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_timestamp`

/// List available USB serial ports
/// Filters to show only USB ports, platform-specific handling
Future<List<PortInfo>> listSerialPorts() =>
    RustLib.instance.api.crateApiSerialListSerialPorts();

/// Open a serial port with the given configuration
Future<String> openPort({required SerialConfig config}) =>
    RustLib.instance.api.crateApiSerialOpenPort(config: config);

/// Close a serial port
Future<String> closePort({required String portName}) =>
    RustLib.instance.api.crateApiSerialClosePort(portName: portName);

/// Send data through a serial port
///
/// # Arguments
/// * `port_name` - Name of the port to send to
/// * `data` - Data string to send
/// * `is_hex` - If true, parse data as hex string (e.g., "48 65 6C 6C 6F")
/// * `byte_delay_us` - Optional inter-byte delay in microseconds (0 = disabled)
Future<String> sendData({
  required String portName,
  required String data,
  required bool isHex,
  BigInt? byteDelayUs,
}) => RustLib.instance.api.crateApiSerialSendData(
  portName: portName,
  data: data,
  isHex: isHex,
  byteDelayUs: byteDelayUs,
);

/// Check if a port is currently open
bool isPortOpen({required String portName}) =>
    RustLib.instance.api.crateApiSerialIsPortOpen(portName: portName);

/// Stream serial data from a port to Flutter via StreamSink
/// This is the key function that replaces Tauri's event emitter
///
/// # Arguments
/// * `port_name` - Name of the port to read from
/// * `baud_rate` - Baud rate (used for calculating gap timeout)
/// * `sink` - StreamSink to send data to Flutter
Stream<SerialData> streamSerialData({
  required String portName,
  required int baudRate,
}) => RustLib.instance.api.crateApiSerialStreamSerialData(
  portName: portName,
  baudRate: baudRate,
);

/// Simple test function to verify bridge works
String greetFromSerial({required String name}) =>
    RustLib.instance.api.crateApiSerialGreetFromSerial(name: name);
