// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Get the global serial state instance
Future<void> getState() => RustLib.instance.api.crateApiStateGetState();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SerialState>>
abstract class SerialState implements RustOpaqueInterface {
  MutexHashMapStringArcMutexBoxSerialPort get ports;

  MutexHashMapStringArcAtomicBool get running;

  set ports(MutexHashMapStringArcMutexBoxSerialPort ports);

  set running(MutexHashMapStringArcAtomicBool running);

  static Future<SerialState> default_() =>
      RustLib.instance.api.crateApiStateSerialStateDefault();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<SerialState> newInstance() =>
      RustLib.instance.api.crateApiStateSerialStateNew();
}
